export default {
  networkErrorTitle: 'Connection Error.',
  serverError : 'There is some issue in server please try again',
  networkErrorMsg:
    'No Internet connection.Make sure that Wi-Fi or mobile data is turned on,then try again.', //"Cannot load data. There is no internet connection.",
  noDataLabel: 'No results found',
  noDataComponent: 'No Data Found',
  subText: "Please click on Plus Button to add the",
  VendorPortal:"VendorMobile",
  EN:"EN",
  apiName:{
    create_new_ticket:"create_new_ticket",
    get_my_tickets:"get_my_tickets",
    add_reply_in_ticket:"add_reply_in_ticket",
    fetch_ticket_details:"fetch_ticket_details",
    get_voucher:"get_voucher",
    vendor_proposal_statistics_count:"vendor_proposal_statistics_count",
    get_my_rfp_list:"get_my_rfp_list",
    vendor_payment_statistic_count: "vendor_payment_statistic_count",
    vendor_payments:"vendor_payments",
    vendor_client_payment_confirmation:"vendor_client_payment_confirmation",
    send_remainder_mail_to_admin:"send_remainder_mail_to_admin",
    get_voucher_version_information:"get_voucher_version_information",
    vendor_voucher_version:"vendor_voucher_version",
    upload_temp_attachment:"upload_temp_attachment",
    add_proposal:"add_proposal"
  },
  icons:{
    bell:"bell",
    filter:"filter",
    menu:"menu",
    eye:"eye",
    ticket_account:"ticket-account",
    telegram:"telegram",
    close:"close",
    clock_time_three:"clock-time-three",
    check_circle:"check-circle",
    close_circle:"close-circle"
  },
  sidemenu: {
    deskboard: "Dashboard",
    proposal: 'Proposals',
    quotation: 'Quotations',
    payment: 'Payments',
    purchase_order: 'Purchase Order',
    eInvoice: 'eInvoice',
    security_terms: 'Security Terms',
    query:'Query',
    catalogue:"Catalogue",
    notification: 'Notification',
    settings: 'Settings',
    logout: 'Logout',
    deliveryPlan: 'Delivery Plan',
    changepassword:'Change password',
    setting:"setting"
  },
  drawer: {
    deskboard: "Dashboard",
    proposal: 'Proposals',
    quotation: 'Quotations',
    payment: 'Payments',
    purchase_order: 'Purchase Order',
    eInvoice: 'eInvoice',
    security_terms: 'Security Terms',
    notification: 'Notification',
    settings: 'Settings',
    query:"Query",
    catalogue:"Catalogue",
    deliveryPlan: 'DeliveryList',
    changepassword:'Change password',
    setting:"setting",
    correspondingAddress:"correspondingAddress",
    contactPersonList:'contactPersonList',
    taxInformation:'taxInformation',
    bankInformation:"bankInformation",
    docInformation:"docInformation"
  },

  screens: {
    signupBasicDetails: {
      interestedTitle: 'Interested to Provide Supplies',
      BusinessProfile: 'BUSINESS PROFILE',
      currency: 'Currency',
      dateTitle: 'Date Of Incorporation',
      communicationTitle: 'COMMUNICATION INDORMATION',
      venderTitle: 'Vendor Name',
      businessFormTitle: 'Form of Business',
      businessTypeTitle: 'Type of Business',
      emailAdress: 'Email Address',
      businessName: 'Registered Business Name',
      webTitle: 'Website URL',
      mobile: 'Mobile Number',
      whatsApp : 'Whatsup Number',
      faxTitle: 'Fax Number',
      buttonText: 'Proceed To Next Step',
      fax_error : 'Please enter correct fax number'
    },
    signUpContactListing: {
      headerText: "CONTACT PERSON",
      buttonTitle: "PROCEED TO NEXT STEP"
    },
    DocumentPopup: {
      documents: 'Documents',
      documents_name: 'Document Name',
      documents_category: 'Document Category',
      expiry_date: 'Expiry Date',
      Attachments: 'Attachments',
      Add: "Add"
    },
    signUpCorrespondingListing: {
      headerText: "CORRESPONDING ADDRESS"
    },
    signUpTaxListing: {
      headerText: "TAX INFORMATION"
    },
    signUpBankingInformationListing: {
      headerText: "BANKING INFORMATION"
    },
    signUpDocumentsListing: {
      headerText: "DOCUMENTS",
      buttonTitle: "COMPLETE SIGN UP"
    },
    otp_verification: {
      otp_verification: "OTP \nVerification",
      sent_access_code: "Please Enter OTP that we have sent in your email ",
      enter_the_otp: "Enter  OTP",
      please_entr_otp: "Please enter OTP",
      please_enter_valid_otp: "Please enter valid OTP",
      didnt_recieve_otp: "Didn't receive the OTP? ",
      resend_otp: "Resend OTP",
      verify_proceed: "Verify & Proceed"
    },
    thankyou: {
      Description: "Thank You For Registering with us. Please find email verification link to your registered email address. Your profile is submitted and under review, we will notify you via email once it will be approved or any correction needed.",
      thankyou: "THANK YOU",
      Vendor: "Vendor",
      Portal: "Portal",
      ok: "OK"
    },
    proposal:{
      request_no:"Request No.",
      version:"Version",
      security_term:"Security Term",
      closer_date:"ClosingDate",
      new_request:"New Request",
      queried:"Queried",
      responded:"Responded",
      win:"Win",
      negotiate:"Negotiate",
      true:"true",
      yes:'yes',
      false:'false',
      deliver_on : "Deliver on:",
      Quality:"Quality:",
      PC:"PC",
      item_spec:"ITEM SPECIFICATION",
      del_loc:"DELIVERY LOCATION",
      rec_name:"Receiver Name",
      emailAdress:"Email Address",
      phone_number:"Phone Number",
      final_amount:"Final Proposal Amount",
      pay_term:"PAYMENT TERMS",
      term_cond:"TERMS & CONDITION",
      attachments:"ATTACHMENTS",
      response:"Response",
      ref_no :"Ref No#"

    },
    query:{
      buttonText:"Raise New Query",
      no_data_msg:"Please click on “Raise New Query” Button to add raises query",
      code:"Code",
      added_date:"Added Date",
      query_comment:"Query Comment",
      raise_query:"Raise Query",
      title:"Query",
      query:'query',
      quotation:'quotation',
      code:"Code",
      added_Date:"Added Date",
      closed:"closed",
      closed_desc:"THIS TICKET HAS BEEN CLOSED...!!",
      description:"Enter description",
      commentError:"Please add Query comment",
      vocherError:"Please select Vocher",
      subject:"Subject",
      voucher:"Voucher",
      open:"open",
      close_text:"This Ticket is Close",
      await_text:"Awaiting for reply from procurement team",
      progress_text:"procurement team responded on your qurey",
    },
    proposal_responce:{
      security_term:"SECURITY TERM",
      notes:"NOTES",
      enter_notes:"Enter Note",
      details:"Details",
      ngn:"NGN (₦)",
      non_taxable_amount:"Non Taxable Amount",
      taxable_amount:"Taxable Amount",
      tax_amount:"Tax Amount",
      edit_responce:"Edit Response",
      add_responce:"Add Response",
      proposal_responce:" Proposal responce"
    },
    payment:{
      voucher_no: "Re# Voucher No.",
      payment_voucher:"Payment Voucher",
      type:"Type",
      plan_date:"Plan Date",
      send_reminder:"Send Reminder",
      advance:"Advance",
      on_receipt:"on receipt",
      on_invoice:"On Invoice",
      amount:"Amount",
      confirm_payment:"Confirm Payment",
      paid_date:"Paid Date",
      from_Account:"From Account",
      to_account:"To Account",
      title:"Payments",
      Approved:"Approved",
      approved:"approved",
      Paid:"Paid",
      paid:"paid",
      Cancelled:"Cancelled",
      cancelled:"cancelled",
      pending:"pending",
      Yes:"Yes",
      No:"No",
      confirm:"confirm",
      confirm_desc:"Please confirm if you received payment?",
      advance_payment:"Advance Payment",
      on_invoice:"On Invoice",
      on_receipt:"On Receipt",
      confirmed:"Confirmed",
      messageError:"Please Write Message",
      reminder_message:"Reminder Message",
      msg_desc:"Enter Message",
      send:"Send",
      recieved:"Received"
    },
    catalogue:{
      no_data_cat_msg: "Please click on \"ADD CATALOGUE\"  Button  to add catalogue",
      buttonText:"Add Catalogue"
    },
    security:{
      buttonText:"Add Term",
      approved:"approved",
      phoneError : 'Please enter correct mobile number',
      no_data_msg: "Please click on \"ADD TERM\"  Button  to add security term",
     
    },
    purchaseOrder :{
      Payment_Voucher : 'Payment Voucher',
      plan_Date :'Plan Date',
      type : 'Type',
      amount : 'Amount',
      closed:"Closed",
      open:"Open"

    },
    notification:{
      active:"Active",
      archive:"Archive"
    }
  } 

};
