export const WHITE = '#FFFFFF';
export const BLACK = '#000000';
export const RED = '#FF3C43';
export const SEPARATOR = '#f1f1f6';
export const PLACEHOLDER = '#B0B7C3';
export const PRIMARY = '#3498db';
export const SECONDARY = '#000000';
export const PRIMARY_BUTTON = '#053EFF';
export const PRIMARY_BUTTON_LIGHT = '#053EFF';
export const INPUT_BG_COLOR = '#ebf0f9';
export const INPUT_TITTLE_COLOR = '#323B4B';
// export const APP_WHITE = '#E5E5E5';
export const GREY_TEXT_COLOR ='#8A94A6';
export const MENU_GROUND = '#4857F4';
export const ALERT_BUTTON_COLOR = '#377DFF';
export const CHIP_ADD_COLOR = '#5F6A86'
export const INPUT = '#222222';
export const CURRENT_CLR= "#053EFF";
export const COMPLETED_CLR ='#053EFF';
export const GREEN ="#38CB89"
export const FLAG_BG ='#f3f3f4';
export const APP_WHITE ='#FAFBFD';
export const ORANGE ='#FF5630';
export const GREY_LIGHT_BACKGROUND ='#C1C6D0';
export const GREY_LIGHT_ORANGE ='#FFF6F4';
export const LIGHT_GREEN="#F5FCF9";
export const LIGHT_ORANGE ="#FFFBF1";
export const LIGHT_BLUE ="#F4F8FF"
export const LIGHT_PURPLE ="#FDF8FF";
export const LIGHT_RED ="#FEF6F4";
export const IN_VOICE = "#FFAB00";
export const RESPONDED ="#C783DF";
export const TAB_COLOR ="#999999";
export const GRAY_COLOR ="#555555";
export const NEW_FLASHED_BLUE ="#053EFF";

