export default {
    Union : require('../../assets/union/Union.png'),
    newvendoricon : require('../../assets/newvendoricon/newvendoricon.png'),
    lockimage : require('../../assets/lockimage/lockimage.png'),
    newlogo : require('../../assets/newlogo/newlogo.png'),
    newsplashlogo : require('../../assets/splashlogo/splashlogo.png'),
    noImage : require('../../assets/no-image.png'),
    spalshlogo: require('../../assets/logo/logo.png'),
    vector: require('../../assets/Vector/Vector.png'),
    pdfLogo: require('../../assets/pdf/pdf.png'),
    Arrow:require('../../assets/Arrow/Arrow.png'),
    ic_dashboard:require('../../assets/ic_dashboard/ic_dashboard.png'),
    ic_proposals:require('../../assets/ic_proposals/ic_proposals.png'),
    ic_quotations:require('../../assets/ic_quotations/ic_quotations.png'),
    ic_payments:require('../../assets/ic_payments/ic_payments.png'),
    ic_purchase_order:require('../../assets/ic_purchase_order/ic_purchase_order.png'),
    ic_einvoice:require('../../assets/ic_einvoice/ic_einvoice.png'),
    ic_security_terms:require('../../assets/ic_security_terms/ic_security_terms.png'),
    ic_notification:require('../../assets/ic_notification/ic_notification.png'),
    ic_settings:require('../../assets/ic_settings/ic_settings.png'),
    ic_logout:require('../../assets/ic_logout/ic_logout.png'),
    sideMenuIcon:require('../../assets/sideMenuIcon/sideMenuIcon.png'),
    Queried:require('../../assets/Queried/Queried.png'),
    Responded:require('../../assets/Responded/Responded.png'),
    message:require('../../assets/message/message.png'),
    call:require('../../assets/call/call.png'),
    monitor:require('../../assets/monitor/monitor.png'),
    query_nodata:require('../../assets/query_nodata/query_nodata.png'),
    img_alert:require('../../assets/img_alert/img_alert.png'),
    img_confirmation:require('../../assets/img_confirmation/img_confirmation.png'),
    img_success:require('../../assets/img_success/img_success.png'),
    Approved:require('../../assets/Approved/Approved.png'),
    Pending:require('../../assets/Pending/Pending.png'),
    Cancelled:require('../../assets/Cancelled/Cancelled.png'),
    Paid:require('../../assets/Paid/Paid.png'),
    payment_info:require('../../assets/payment_info/payment_info.png'),
    delivery_info:require('../../assets/delivery/delivery.png'),    
    rejected : require('../../assets/rejected/rejected.png'),

    purchase_cencel : require('../../assets/purchase_cencel/Group.png'),
    purchase_Delivered : require('../../assets/purchase_Delivered/Group.png'),
    purchase_delivery_pending : require('../../assets/purchase_delivery_pending/Group.png'),
    purchase_pending_plan : require('../../assets/purchase_pending_plan/Group.png'),
    ic_catalogue:require('../../assets/ic_catalogue/ic_catalogue.png'),
    Negotiate:require('../../assets/Negotiate/Negotiate.png'),
    ic_incomplete:require('../../assets/ic_incomplete/ic_incomplete.png'),
    ic_completed:require('../../assets/ic_completed/ic_completed.png'),
    ic_change_password:require('../../assets/ic_change_password/ic_change_password.png'),
    ic_corresponding_address:require('../../assets/ic_corresponding_address/ic_corresponding_address.png'),
    ic_contact_person:require('../../assets/ic_contact_person/ic_contact_person.png'),
    ic_taxation_information:require('../../assets/ic_taxation_information/ic_taxation_information.png'),
    ic_banking_information:require('../../assets/ic_banking_information/ic_banking_information.png'),
    ic_documents:require('../../assets/ic_documents/ic_documents.png')
    
};
